Add Ruby versions 2.6.10, 2.7.6, 3.0.4
GoogleCloudPlatform/ruby-docker pull request #218
Opened 2022-04-27 21:52 UTC by ain

- https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-6-10-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-2-7-6-released/
- https://www.ruby-lang.org/en/news/2022/04/12/ruby-3-0-4-released/

2022-04-27 22:38 UTC, amurciasu requested changes

2022-04-27 22:38 UTC, amurciasu commented on ruby-pipeline/ruby-latest.yaml
> +           '--prebuilt-image=2.6.9=gcr.io/gcp-runtimes/ruby/ubuntu16/prebuilt/ruby-2.6.10:latest',
```suggestion
           '--prebuilt-image=2.6.10=gcr.io/gcp-runtimes/ruby/ubuntu16/prebuilt/ruby-2.6.10:latest',
```

2022-04-27 22:38 UTC, amurciasu commented on ruby-pipeline/ruby-latest.yaml
> +           '--prebuilt-image=2.7.5=gcr.io/gcp-runtimes/ruby/ubuntu16/prebuilt/ruby-2.7.6:latest',
```suggestion
           '--prebuilt-image=2.7.6=gcr.io/gcp-runtimes/ruby/ubuntu16/prebuilt/ruby-2.7.6:latest',
```

2022-04-27 22:43 UTC, amurciasu approved these changes

2022-05-12 13:02 UTC, ain commented
@dazuma are you perhaps available to merge this one as well? 

`2.7.6` included [CVE-2022-28739](https://www.ruby-lang.org/en/news/2022/04/12/buffer-overrun-in-string-to-float-cve-2022-28739/) that would make it quite relevant to ship, replacing the former pre-built images.

2022-06-03 21:19 UTC, dazuma commented
This was handled by #222. The runtime release will happen next week, either June 7 or June 8.

2022-06-03 21:19 UTC, closed without merging